from talon import actions, Module, Context

steps_monitor_one = {
    "zero": 5,
    "act": 50,
    'alpha': 50,
    "bat": 100,
    "bravo": 100,
    "cat": 150,
    "charlie": 150,
    "drum": 200,
    "delta" : 200,
    "echo": 250,
    "eve": 250,
    "fox": 300,
    "foxtrot": 300,
    "golf": 350,
    "hot": 400,
    "hotel": 400,
    "sit": 450,
    "india": 450,
    "jury": 500,
    "juliet": 500,
    "crunch": 550,
    "kilo": 550,
    "look": 600,
    "lima": 600,
    "mike": 650,
    "near": 700,
    "November": 700,
    "odd": 750,
    "oscar": 750,
    "pit": 800,
    "papa": 800,
    "quench": 850,
    "quebec": 850,
    "red": 900,
    "romeo": 900,
    "sun": 950,
    "sierra": 950,
    "trap": 1000,
    "tango": 1000,
    "urge": 1050,
    "uniform": 1050,
    "vest": 1100,
    "victor": 1100,
    "whale": 1150,
    "whiskey": 1150,
    "plex": 1200,
    "xray": 1200,
    "yank": 1250,
    "yankee": 1250,
    "zip": 1300,
    "zulu": 1300,
    "one":1350,
    "two":1400,
    "three":1450,
    "four":1500,
    "five":1550,
    "six":1600,
    "seven":1650,
}
steps_monitor_two = {
    "eight":1700,
    "nine":1750,
    "ten":1790,
    "eleven":1840,
    "twelve":1890,
    "thirteen":1940,
    "fourteen":1990,
    "fifteen":2040,
    "sixteen":2090,
    "seventeen":2130,
    "eighteen":2180,
    "nineteen":2230,
    "twenty":2280,
    "twenty one":2330,
    "twenty two":2380,
    "twenty three":2430,
    "twenty four":2480,
    "twenty five":2530,
    "twenty six":2570,
    "twenty seven":2620,
    "twenty eight":2670, 
    "twenty nine":2720,
    "thirty":2770,
    "thirty one":2810,
    "thirty two":2860,
    "thirty three":2910,
    "thirty four":2960,
    "thirty five":3010,
    "thirty six":3060,
    "thirty seven":3100,
    "thirty eight":3150,
    "thirty nine":3200,
    "forty":3250,
    "forty one":3300,
    "forty two":3350,
    "forty three":3400,
    "forty four":3450,
    "forty five":3490,
    "forty six":3540,
    "forty seven":3590
    }

steps_monitor_two_commandconquer = {
    "eight":1700,
    "nine":1740,
    "ten":1770,
    "eleven":1800,
    "twelve":1870,
    "thirteen":1940,
    "fourteen":1980,
    "fifteen":2000,
    "sixteen":2040,
    "seventeen":2070,
    "eighteen":2120,
    "nineteen":2140,
    "twenty":2210,
    "twenty one":2250,
    "twenty two":2300,
    "twenty three":2340,
    "twenty four":2390,
    "twenty five":2430,
    "twenty six":2470,
    "twenty seven":2510,
    "twenty eight":2550, 
    "twenty nine":2590,
    "thirty":2640,
    "thirty one":2608,
    "thirty two":2720,
    "thirty three":2760,
    "thirty four":2800,
    "thirty five":2850,
    "thirty six":2890,
    "thirty seven":2920,
    "thirty eight":2970,
    "thirty nine":3020,
    "forty":3060,
    "forty one":3100,
    "forty two":3140,
    "forty three":3190,
    "forty four":3230,
    "forty five":3270,
    "forty six":3310,
    "forty seven":3350
    }

is_second_monitor = {
    "zero": False,
    "act": False,
    'alpha': False,
    "bat": False,
    "bravo": False,
    "cat": False,
    "charlie": False,
    "drum": False,
    "delta" : False,
    "echo": False,
    "eve": False,
    "fox": False,
    "foxtrot": False,
    "golf": False,
    "hot": False,
    "hotel": False,
    "sit": False,
    "india": False,
    "jury": False,
    "juliet": False,
    "crunch": False,
    "kilo": False,
    "look": False,
    "lima": False,
    "mike": False,
    "near": False,
    "November": False,
    "odd": False,
    "oscar": False,
    "pit": False,
    "papa": False,
    "quench": False,
    "quebec": False,
    "red": False,
    "romeo": False,
    "sun": False,
    "sierra": False,
    "trap": False,
    "tango": False,
    "urge": False,
    "uniform": False,
    "vest": False,
    "victor": False,
    "whale": False,
    "whiskey": False,
    "plex": False,
    "xray": False,
    "yank": False,
    "yankee": False,
    "zip": False,
    "zulu": False,
    "one":False,
    "two":False,
    "three":False,
    "four":False,
    "five":False,
    "six":False,
    "seven":False,
    "eight":True,
    "nine":True,
    "ten":True,
    "eleven":True,
    "twelve":True,
    "thirteen":True,
    "fourteen":True,
    "fifteen":True,
    "sixteen":True,
    "seventeen":True,
    "eighteen":True,
    "nineteen":True,
    "twenty":True,
    "twenty one":True,
    "twenty two":True,
    "twenty three":True,
    "twenty four":True,
    "twenty five":True,
    "twenty six":True,
    "twenty seven":True,
    "twenty eight":True, 
    "twenty nine":True,
    "thirty":True,
    "thirty one":True,
    "thirty two":True,
    "thirty three":True,
    "thirty four":True,
    "thirty five":True,
    "thirty six":True,
    "thirty seven":True,
    "thirty eight":True,
    "thirty nine":True,
    "forty":True,
    "forty one":True,
    "forty two":True,
    "forty three":True,
    "forty four":True,
    "forty five":True,
    "forty six":True,
    "forty seven":True,
}

steps_vertical = {
    "zero": 5,
    "act": 50,
    "alpha": 50,
    "bat": 100,
    "bravo": 100,
    "cat": 150,
    "charlie": 150,
    "drum": 200,
    "delta" : 200,
    "echo": 250,
    "eve": 250,
    "fox": 300,
    "foxtrot": 300,
    "golf": 350,
    "hot": 400,
    "hotel": 400,
    "sit": 450,
    "india": 450,
    "jury": 500,
    "juliet": 500,
    "crunch": 550,
    "kilo": 550,
    "look": 600,
    "lima": 600,
    "mike": 650,
    "near": 700,
    "November": 700,
    "odd": 750,
    "oscar": 750,
    "pit": 800,
    "papa": 800,
    "quench": 850,
    "quebec": 850,
    "red": 900,
    "romeo": 900,
    "sun": 950,
    "sierra": 950,
    "trap": 1000,
    "tango": 1000,
    "urge": 1050,
    "uniform": 1050,
}

steps_vertical_monitor_two = {
    "zero": 5,
    "act": 50,
    "alpha": 50,
    "bat": 85,
    "bravo": 85,
    "cat": 140,
    "charlie": 140,
    "drum": 195,
    "delta" : 195,
    "echo": 250,
    "eve": 250,
    "fox": 300,
    "foxtrot": 300,
    "golf": 350,
    "hot": 405,
    "hotel": 405,
    "sit": 455,
    "india": 455,
    "jury": 505,
    "juliet": 505,
    "crunch": 555,
    "kilo": 555,
    "look": 605,
    "lima": 605,
    "mike": 655,
    "near": 705,
    "November": 705,
    "odd": 755,
    "oscar": 755,
    "pit": 805,
    "papa": 805,
    "quench": 855,
    "quebec": 855,
    "red": 905,
    "romeo": 905,
    "sun": 955,
    "sierra": 955,
    "trap": 1005,
    "tango": 1005,
    "urge": 1055,
    "uniform": 1055,
}

mod = Module()
mod.list("screen_step_one", desc="location on screen edge monitor one")
mod.list("screen_step_two", desc="location on screen edge monitor two")
mod.list("screen_step_two_commandconquer", desc="location on screen edge monitor two with 1680 width in old game C&C")

mod.list("screen_step_vertical", desc="location on screen Vertical edge")

mod.list("screen_step_vertical_monitor_two", desc="location on screen Vertical edge monitor two")

ctx = Context()
ctx.lists["user.screen_step_one"] = list(steps_monitor_one.keys())
ctx.lists["user.screen_step_two"] = list(steps_monitor_two.keys())
ctx.lists["user.screen_step_two_commandconquer"] = list(steps_monitor_two_commandconquer.keys())

ctx.lists["user.screen_step_vertical"] = list(steps_vertical.keys())

ctx.lists["user.screen_step_vertical_monitor_two"] = list(steps_vertical_monitor_two.keys())

@mod.capture(rule="{user.screen_step_one}")
def screen_step_one(m) -> int:
    "Get horizontal pixel screen coordinate for monitor one"
    actual=steps_monitor_one[m.screen_step_one] - 1680
    return actual

@mod.capture(rule="{user.screen_step_two}")
def screen_step_two(m) -> int:
    "Get horizontal pixel screen coordinate for monitor two"
    actual=steps_monitor_two[m.screen_step_two] - 1680
    return actual

@mod.capture(rule="{user.screen_step_two_commandconquer}")
def screen_step_two_commandconquer(m) -> int:
    "Get horizontal pixel screen coordinate for monitor two with 1680 width in old game C&C"
    actual=steps_monitor_two_commandconquer[m.screen_step_two_commandconquer] - 1680
    return actual

@mod.capture(rule="{user.screen_step_vertical}")
def screen_step_vertical(m) -> int:
    "Get vertical pixel screen coordinate"
    return steps_vertical[m.screen_step_vertical]    

@mod.capture(rule="{user.screen_step_vertical_monitor_two}")
def screen_step_vertical_monitor_two(m) -> int:
    "Get vertical pixel screen coordinate"
    return steps_vertical_monitor_two[m.screen_step_vertical_monitor_two]    

@mod.capture(rule="{user.is_second_monitor}")
def is_second_monitor(m) -> bool:
    return is_second_monitor[m.is_second_monitor]

