from talon import Module, Context

mod = Module()
mod.list("snippet_category", desc="Custom Snippet Categories")

ctx_default = Context()
ctx_default.lists["user.snippet_category"] = {
"Access":"Access",
"Action Filters":"Action Filters",
"Action":"Action",
"ActiveX Data Objects":"ActiveX Data Objects",
"Attributes":"Attributes",
"Bald Bearded Builder":"Bald Bearded Builder",
"Blocks":"Blocks",
"C# Fritz":"C# Fritz",
"ClarkIO":"ClarkIO",
"Class":"Class",
"Code":"Code",
"CodeRushed":"CodeRushed",
"Commands":"Commands",
"Computer Names":"Computer Names",
"Connection Strings":"Connection Strings",
"Data Access Objects":"Data Access Objects",
"Data Annotations":"Data Annotations",
"Data Definition Language":"Data Definition Language",
"Database Names":"Database Names",
"Date Functions":"Date Functions",
"DB Contexts":"DB Contexts",
"Dev Folders":"Dev Folders",
"Domain Functions":"Domain Functions",
"Dragon":"Dragon",
"DSN Files":"DSN Files",
"File Extensions":"File Extensions",
"Files":"Files",
"Fluent API":"Fluent API",
"Folders":"Folders",
"Functions":"Functions",
"Hypertext Helper":"Hypertext Helper",
"Language Integrated Query":"Language Integrated Query",
"LaylaCodesIt":"LaylaCodesIt",
"Logical Functions":"Logical Functions",
"Migration Commands":"Migration Commands",
"No Longer Used":"No Longer Used",
"NPM Commands":"NPM Commands",
"Open Forms":"Open Forms",
"Open Objects":"Open Objects",
"Operators":"Operators",
"Passwords":"Passwords",
"Property":"Property",
"Regular Expressions":"Regular Expressions",
"Return":"Return",
"Sample Data":"Sample Data",
"Select":"Select",
"Server Names":"Server Names",
"Snippet":"Snippet",
"Staging Servers":"Staging Servers",
"Statements":"Statements",
"String Functions":"String Functions",
"Structured Query Language":"Structured Query Language",
"System Command":"System Command",
"Tag Helper":"Tag Helper",
"Tags":"Tags",
"Tags Secondary":"Tags Secondary",
"Text":"Text",
"Transitions and Transformation":"Transitions and Transformation",
"URLs":"URLs",
"Useful Functions":"Useful Functions",
"Useful Sub Routines":"Useful Sub Routines",
"Usernames":"Usernames",
"VBA":"VBA",
"Words":"Words",

}

