app.exe: msaccess.exe
-

# Navigation and Views
datasheet view:
    key(alt-h)
    sleep(100ms)
    key(w)
    sleep(100ms)
    key(h)
design view:
    key(alt-h)
    sleep(100ms)
    key(w)
    sleep(100ms)
    key(d)
form view: key(f5)
nav pane | navigation [menu]: key(f11)
prop sheet: key(f4)
next pane: key(f6)
next view: key(ctrl-right)
prior view: key(ctrl-left)
field list: key(alt-f8)
close window: key(ctrl-w)
code editor: key(alt-f11)
toggle (code | coat) [editor]: key(alt-f11)
zoom box: key(shift-f2)
zoom in: key(ctrl-alt-+)
zoom out: key(ctrl-alt--)
duplicate: key(ctrl-@)
# Find and Replace
find replace: key(ctrl-h)
find next: key(shift-f4)
find next <user.number_string>:
    key(ctrl-f)
    sleep(100ms)
    insert(number_string)
    sleep(100ms)
    key(alt-n)
    sleep(100ms)
    key(escape)

dropdown [list]: key(alt-down)
property [sheet]: key(f4)

# Data Entry
date stamp: key(ctrl-;)
time stamp: key(ctrl-shift-;)
new record: key(ctrl-shift-=)
delete record: key(ctrl-minus)
save record: key(shift-enter)
ditto field: key(ctrl-')
default value: key(ctrl-alt-space)

# Record Navigation
first record: key(ctrl-home)
last record: key(ctrl-end)
re query: key(shift-f9)
edit mode: key(f2)

# VBA Debugging
step into: key(f8)
step over: key(shift-f8)
step out: key(ctrl-shift-f8)
run to cursor: key(ctrl-f8)
break [in] code: user.break_in_code()

[toggle] breakpoint: key(f9)
continue: key(f5)
clear all breakpoints: key(ctrl-shift-f9)
compile [code]:
    key(alt-d)
    sleep(100ms)
    key(c)
immediate [window]: key(ctrl-g)
reset code:
    key(alt-d)
    sleep(100ms)
    key(right)
    sleep(100ms)
    key(r)

# VBA Editor
browse objects: key(f2)
project pane: key(ctrl-r)
quick watch: key(shift-f9)
complete word: key(ctrl-space)
quick info: key(ctrl-i)
param info: key(ctrl-shift-i)
last position: key(ctrl-shift-f2)
list members: key(ctrl-j)
list constants: key(ctrl-shift-j)
import file: key(ctrl-m)
export file: key(ctrl-e)
view design: key(shift-f7)
view code: key(f7)
[go to] definition: key(shift-f2)
set next statement: key(ctrl-f9)
hunt (all | this): key(ctrl-f)
open [an] object:
    user.mouse_helper_position_save()
    user.mouse_helper_move_image_relative("2026-02-18_10.33.23.559138.png", 0)
    sleep(0.05)
    mouse_click(0)
    sleep(0.05)
    user.mouse_helper_position_restore()
click form view:
    user.mouse_helper_position_save()
    user.mouse_helper_move_image_relative("2026-02-18_10.36.24.178602.png", 0)
    sleep(0.05)
    mouse_click(0)
    sleep(0.05)
    user.mouse_helper_position_restore()
click datasheet [view]:
    user.mouse_helper_position_save()
    user.mouse_helper_move_image_relative("2026-02-18_10.37.45.831298.png", 0)
    sleep(0.05)
    mouse_click(0)
    sleep(0.05)
    user.mouse_helper_position_restore()
click design [view]:
    user.mouse_helper_position_save()
    user.mouse_helper_move_image_relative("2026-02-18_10.39.28.164029.png", 0)
    sleep(0.05)
    mouse_click(0)
    sleep(0.05)
    user.mouse_helper_position_restore()
click ellipse:
    user.mouse_helper_position_save()
    user.mouse_helper_move_image_relative("2026-02-18_11.07.01.738239.png", 0)
    sleep(0.05)
    mouse_click(0)
    sleep(0.05)
    user.mouse_helper_position_restore()
click navigation form:
    user.mouse_helper_position_save()
    user.mouse_helper_move_image_relative("2026-02-18_11.19.17.935005.png", 0)
    sleep(0.05)
    mouse_click(0)
    sleep(0.05)
    user.mouse_helper_position_restore()
# To be used in datasheet view to best fit the column width to the content
best fit:
    key(ctrl-a)
    sleep(200ms)
    key(alt)
    sleep(200ms)
    key(h)
    sleep(200ms)
    key(p)
    sleep(200ms)
    key(f)
    sleep(200ms)
    key(alt-b)
chain login:
    key(shift-tab)
    sleep(200ms)
    insert("axxonlab")
    sleep(200ms)
    key(tab)
    sleep(200ms)
    insert("uygfuiHqduf40")
    sleep(200ms)
    key(enter)
down space:
    key(down)
    sleep(200ms)
    key(space)
tab space:
    key(tab)
    sleep(200ms)
    key(space)
space tab:
    key(space)
    sleep(200ms)
    key(tab)
tab next: key(ctrl-f6)
tab previous: key(ctrl-shift-f6)
toggle bookmark:
    key(alt-e)
    sleep(200ms)
    key(b)
    sleep(200ms)
    key(t)
next bookmark:
    key(alt-e)
    sleep(200ms)
    key(b)
    sleep(200ms)
    key(n)
previous bookmark:
    key(alt-e)
    sleep(200ms)
    key(b)
    sleep(200ms)
    key(p)
error setting:
    key(alt-t)
    sleep(200ms)
    key(o)
    sleep(200ms)
    key(ctrl-tab:2)
    sleep(200ms)
    key(alt-b)
take word: key(ctrl-shift-right)
take tail: key(shift-end)
(enzad | nz) function number: user.apply_selection_function("Nz")
(enzad | nz) function string: user.apply_selection_function("Nz", "")
(nvl | null value) function number: user.apply_selection_function("Nvl")
(nvl | null value) function string: user.apply_selection_function("Nvl", "")
trim function: user.apply_selection_function("Trim")
length function: user.apply_selection_function("Len")
lower case function: user.apply_selection_function("LCase")
upper case function: user.apply_selection_function("UCase")
string function: user.apply_selection_function("CStr")
integer function: user.apply_selection_function("CInt")
long function: user.apply_selection_function("CLng")
double function: user.apply_selection_function("CDbl")
absolute function: user.apply_selection_function("Abs")
format function: user.apply_selection_function("Format")
left function: user.apply_selection_function("Left")
right function: user.apply_selection_function("Right")
year function: user.apply_selection_function("Year")
month function: user.apply_selection_function("Month")
day function: user.apply_selection_function("Day")
date value function: user.apply_selection_function("DateValue")
string value function: user.apply_selection_function("Str")
value function: user.apply_selection_function("Val")
end if back:
    key(end)
    sleep(200ms)
    key(enter)
    sleep(200ms)
    insert("End If")
take head: key(shift-home)
ampersands in:
    insert(" &  & ")
    sleep(200ms)
    key(left:3)
